# -*-coding:utf-8 -*-
# Author:王茂波
# function:常量
# 坐标原点
COORDINATE_X = 0
COORDINATE_Y = 0
# 背景图大小
BACKGROUND_WIDTH = 480
BACKGROUND_HEIGHT = 852
# 难度系数-两帧之间的延迟
DIFFICULT_LEVEL = 0.01
# 单位长度
UNIT_LEN = 100
# 概率基数
BASE_POSSIBILITY = 1000
# 玩家飞机初始坐标
INITIAL_PLAYER_X = 210
INITIAL_PLATER_Y = 700
# 玩家飞机宽高
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 124
# 敌机参数
EMENY0_WIDTH = 51
EMENY0_HEIGHT = 39
EMENY1_WIDTH = 69
EMENY1_HEIGHT = 89
EMENY2_WIDTH = 165
EMENY2_HEIGHT = 246
# 敌机子弹高度
EMEMY0_BULLET_HEIGHT = 21
# 我方的得分
ENEMY0_DEATH_SCORE = 10
ENEMY1_DEATH_SCORE = 20
ENEMY2_DEATH_SCORE = 50
# 难度系数-玩家移动系数
PLAYER_MOVE_FACTOR = 0.3
# 难度系数-玩家子弹移动速度系数
PLAYER_BULLET_MOVE_FACTOR = 0.1
# 难度系数-敌机移动系数
ENEMY_MOVE_FACTOR = 0.02
# 难度系数-敌机子弹移动速度系数
ENEMY_BULLET_MOVE_FACTOR = 0.02
# 难度系数-敌机的子弹密集度
ENEMY_BULLET_DENSITY = 0.3
# 难度系数-敌机密集度
ENEMY_DENSITY = 0.6
